### ISSUE TITLE
githubになれよう！

### ISSUE THREAD

**Issue by mizmarine** [mizmarine/positivery#3]
今時githubもさわれないのは小学生までだよね〜

ってことで みんな遊んでみるといいよ

各位招待してなにかしらcommentしたらclose

**Comment by mizmarine** [comment]
invite

- [x] zai
- [x] tomio
- [x] yutaro
- [ ] mamoru

**Comment by tomio-hamada** [comment]
zaiって週刊誌にありそうな名前

**Comment by kooozai1028** [comment]
tomisan www

**Comment by yutaro0121** [comment]
おし！

**Comment by mizmarine** [comment]
wiwi
