### ISSUE TITLE
gitも使えるようになろう！

### ISSUE THREAD

**Issue by mizmarine** [mizmarine/positivery#4]
せっかくなのでgitつかえるようになろうよってやつ

**Comment by mizmarine** [comment]
まずは homebrewいれるのがいいかな

**Comment by tomio-hamada** [comment]
homebrewとは？

**Comment by mizmarine** [comment]
- mac向けの
- 色々なアプリケーションを管理できるコマンド

って感じかな

**Comment by mizmarine** [comment]
https://brew.sh/index_ja.html

**Comment by mizmarine** [comment]
```
which brew
```
でhomebrew入ってることを確認したら

```
brew install git
```
とかするといいと想うよ（雑

---

なおwindowsは知らん勝手に頑張れ（

**Comment by mizmarine** [comment]
git コマンドが入ったら githubにSSH鍵を登録しましょう

**Comment by mizmarine** [comment]
SSH鍵の生成はこの辺を見るのじゃ
https://help.github.com/articles/connecting-to-github-with-ssh/

**Comment by mizmarine** [comment]
ssh key 登録できたら

https://github.com/mizmarine/positively を git cloneするのじゃ

**Comment by mizmarine** [comment]
cloneしたら
https://github.com/mizmarine/positively/blob/master/api/readme.md
を見るのじゃ

**Comment by mizmarine** [comment]
ってことで ざい環境でうごいたのでok
途中pyenv-vertualenv入ってない落とし穴とかあったけどそのへんはよしなに。

はやくdockerizeしよう。
